# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 564016c2d1968bd812532b13b4f8735d5cb70b9ee4accb298a5dddbccb1f447a1480ad0bf0df7af9e8b0d54ac74f6cd5cddb297cea9bf253a38c632d18a21ba0

test:
  secret_key_base: 236958f0cf0899a20f95bbda3b43f86857c0ab1290ae3dc80d16db482e258496f6e65b07caf934cc009ca6542d0c4bde44dd5576c5d4c5564a1d5fefc546a034

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
